### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by aress31** [LeonardoNve/sslstrip2#10]
Hi,
I am working on the android tls security for my master thesis and I would really need this version of sslstrip defeating hsts. Could you please send me the package by email if I give you my email address?
If you need proof of my master thesis subject I can send you official papers from my University.

**Comment by aress31** [comment]
So Leonardo is it possible? I really need to demonstrate the security flaws in the android apps and there is no way to overpass HSTS except using your software so I really need it.

**Comment by byt3bl33d3r** [comment]
@AresS31 because of a new law where he lives, I don't think he can email it to you.. if you want, you can try out a project of mine that implements his work https://github.com/byt3bl33d3r/MITMf

**Comment by aress31** [comment]
I saw that thanks but I only need sslstrip2+ because I am doing my own framework and I only need this plugin could you email it to me @byt3bl33d3r alongside with his dns program? :)

**Comment by byt3bl33d3r** [comment]
@AresS31 I only have a copy of sslstrip2 , your going to have to search around for dns2proxy if you need it, drop me an email at byt3bl33d3r@gmail.com and I'll send it to you

**Comment by aress31** [comment]
I could get them thank you very much! :) Now go to work ^^
